version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
