# Generated by Django 5.2.4 on 2025-07-19 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chats', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_rooms', to=settings.AUTH_USER_MODEL)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
